import { DefaultSerializeable } from 'scandit-react-native-datacapture-core/js/private/Serializeable';
import { BarcodePickViewHighlightStyle } from './BarcodePickViewHighlightStyle';
export declare class BarcodePickViewSettings extends DefaultSerializeable {
    private _highlightStyle;
    private _showLoadingDialog;
    private _loadingDialogText;
    private _showGuidelines;
    private _initialGuidelineText;
    private _moveCloserGuidelineText;
    private _showHints;
    private _onFirstItemToPickFoundHintText;
    private _onFirstItemPickCompletedHintText;
    private _onFirstUnmarkedItemPickCompletedHintText;
    private _onFirstItemUnpickCompletedHintText;
    private constructor();
    get highlightStyle(): BarcodePickViewHighlightStyle;
    set highlightStyle(style: BarcodePickViewHighlightStyle);
    get showLoadingDialog(): boolean;
    set showLoadingDialog(style: boolean);
    get loadingDialogText(): string;
    set loadingDialogText(text: string);
    get showGuidelines(): boolean;
    set showGuidelines(show: boolean);
    get initialGuidelineText(): string;
    set initialGuidelineText(text: string);
    get moveCloserGuidelineText(): string;
    set moveCloserGuidelineText(text: string);
    get showHints(): boolean;
    set showHints(show: boolean);
    get onFirstItemToPickFoundHintText(): string;
    set onFirstItemToPickFoundHintText(text: string);
    get onFirstItemPickCompletedHintText(): string;
    set onFirstItemPickCompletedHintText(text: string);
    get onFirstUnmarkedItemPickCompletedHintText(): string;
    set onFirstUnmarkedItemPickCompletedHintText(text: string);
    get onFirstItemUnpickCompletedHintText(): string;
    set onFirstItemUnpickCompletedHintText(text: string);
}
