import { Feedback } from 'scandit-react-native-datacapture-core/js/Feedback';
export declare const BarcodeCountDefaults: {
    Feedback: {
        success: Feedback;
        failure: Feedback;
    };
    BarcodeCountSettings: {
        expectOnlyUniqueBarcodes: any;
        disableModeWhenCaptureListCompleted: any;
        barcodeFilterSettings: any;
    };
    BarcodeCountView: {
        shouldShowUserGuidanceView: any;
        shouldShowListButton: any;
        shouldShowExitButton: any;
        shouldShowShutterButton: any;
        shouldShowHints: any;
        shouldShowClearHighlightsButton: any;
        shouldShowSingleScanButton: any;
        shouldShowFloatingShutterButton: any;
        shouldShowToolbar: any;
        defaultNotInListBrush: any;
        defaultRecognizedBrush: any;
        defaultUnrecognizedBrush: any;
        shouldShowScanAreaGuides: any;
        clearHighlightsButtonText: any;
        exitButtonText: any;
        textForUnrecognizedBarcodesDetectedHint: any;
        textForTapShutterToScanHint: any;
        textForScanningHint: any;
        textForMoveCloserAndRescanHint: any;
        textForMoveFurtherAndRescanHint: any;
        toolbarSettings: {
            audioOnButtonText: any;
            audioOffButtonText: any;
            audioButtonContentDescription: any;
            audioButtonAccessibilityHint: any;
            audioButtonAccessibilityLabel: any;
            vibrationOnButtonText: any;
            vibrationOffButtonText: any;
            vibrationButtonContentDescription: any;
            vibrationButtonAccessibilityHint: any;
            vibrationButtonAccessibilityLabel: any;
            strapModeOnButtonText: any;
            strapModeOffButtonText: any;
            strapModeButtonContentDescription: any;
            strapModeButtonAccessibilityHint: any;
            strapModeButtonAccessibilityLabel: any;
            colorSchemeOnButtonText: any;
            colorSchemeOffButtonText: any;
            colorSchemeButtonContentDescription: any;
            colorSchemeButtonAccessibilityHint: any;
            colorSchemeButtonAccessibilityLabel: any;
        };
        listButtonAccessibilityHint: any;
        listButtonAccessibilityLabel: any;
        listButtonContentDescription: any;
        exitButtonAccessibilityHint: any;
        exitButtonAccessibilityLabel: any;
        exitButtonContentDescription: any;
        shutterButtonAccessibilityHint: any;
        shutterButtonAccessibilityLabel: any;
        shutterButtonContentDescription: any;
        floatingShutterButtonAccessibilityHint: any;
        floatingShutterButtonAccessibilityLabel: any;
        floatingShutterButtonContentDescription: any;
        clearHighlightsButtonAccessibilityHint: any;
        clearHighlightsButtonAccessibilityLabel: any;
        clearHighlightsButtonContentDescription: any;
        singleScanButtonAccessibilityHint: any;
        singleScanButtonAccessibilityLabel: any;
        singleScanButtonContentDescription: any;
    };
};
